select * from customer limit 20

--using ALTER filter to change the attribute names from capital to lower and spaces to "_"

alter table customer rename column "Customer ID" to customer_id;
alter table customer rename column "Age" to age;
alter table customer rename column "Gender" to gender;
alter table customer rename column "Item Purchased" to item_purchased;
alter table customer rename column "Category" to category;
alter table customer rename column "Location" to location;
alter table customer rename column "Purchase Amount (USD)" to purchase_amount;
alter table customer rename column "Size" to size;
alter table customer rename column "Color" to color;
alter table customer rename column "Season" to season;
alter table customer rename column "Review Rating" to review_rating;
alter table customer rename column "Subscription Status" to subscription_status;
alter table customer rename column "Shipping Type" to shipping_type;
alter table customer rename column "Discount Applied" to discount_applied;
alter table customer rename column "Promo Code Used" to promo_code_used;
alter table customer rename column "Previous Purchases" to previous_purchases;
alter table customer rename column "Payment Method" to payment_method;
alter table customer rename column "Frequency of Purchases" to frequency_of_purchases;

--Q1. What is the total revenue generated by male vs. feamle customers?
select gender , SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchage amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchage Amount between Standard and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do Subscribed Customers spend more? Compare average spend and total reveue between subscriptions and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(AVG(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 Products have the highest percentage of purchases wuth discounts applied?
select item_purchased,
ROUND(100 * SUm(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New,Returning, and Loyal based on their total number of previous purchases,
--and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases =1 THEn 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the Top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC )  as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who repeat buyers (more than 5 purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10. What is the revenur contribution of each Age group?
select 
	CASE 
		WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
        WHEN age BETWEEN 31 AND 45 THEN 'Middle-aged'
        WHEN age BETWEEN 46 AND 60 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;